name: payment_checkout
description: This package simplifies integrating PayPal payments into your
  mobile app. Key features include seamless in-app PayPal integration
homepage: https://github.com/mahmoudbakir2015/payment_checkout
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  firebase_core: ^2.22.0
  flutter_bloc: ^8.1.3
  flutter_credit_card: ^4.0.1
  flutter_inappwebview: ^5.8.0
  flutter_stripe: any
  pretty_dio_logger: ^1.3.1
  svg_flutter: ^0.0.1
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_messaging: ^14.7.4
  shared_preferences: ^2.2.2
  firebase_database: ^10.3.4
  flutter_paypal_payment: ^1.0.6
  
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
